# Generated by Django 2.0.6 on 2021-08-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('pk_restaurant', models.AutoField(primary_key=True, serialize=False)),
                ('saucer', models.CharField(max_length=50)),
                ('invoice', models.TextField()),
                ('employee', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fk_product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fk_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='saucer',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='fk_restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant'),
            preserve_default=False,
        ),
    ]
