# Generated by Django 2.0.6 on 2021-09-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210825_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='invoice',
        ),
    ]
