# Generated by Django 2.0.6 on 2021-09-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_restaurant_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='client',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fk_restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='saucer',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
