# Generated by Django 2.0.6 on 2021-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://d1uz88p17r663j.cloudfront.net/resized/D60D6F76-811C-6377-B9D8-FF0000673B69-500x295-b-principal_1200_600.png', max_length=8000),
        ),
    ]
