# Generated by Django 2.0.6 on 2021-09-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_producto',
            fields=[
                ('pk_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
