# Generated by Django 2.0.6 on 2021-09-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fk_tipo_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.tipo_producto'),
            preserve_default=False,
        ),
    ]
